const { Router } = require('express')
const verifyTokenDoctor = require('../middlewares/TokenVerifyDoctor')
const verifyToken = require('../middlewares/TokenVerify')
const { listMedicalAppo, insertMedicAppo,deleteMedicappo,updateMedicappo,listMedicAppoIdDoctor,listMedicAppoByIdPatient,deleteMedicalAppointmentByDoctor , deleteMedicalAppointmentByPaciente} = require('../controllers/MedicalappointmentController')
const router = Router()
router.get('/medicalappointment/listMedicalAppo', listMedicalAppo)
router.post('/medicalappointment/insertMedicAppo', insertMedicAppo)
router.delete('/medicalappointment/deleteMedicappo/:medicalappoid',verifyToken, deleteMedicappo)
router.put('/medicalappointment/updateMedicappo/:medicalappoid',verifyTokenDoctor, updateMedicappo)
router.get('/medicalappointment/listMedicalAppobyid/doctor/:idDoctor', verifyTokenDoctor, listMedicAppoIdDoctor)
router.get('/medicalappointment/listMedicalAppobyid/patient/:idPatient', verifyToken, listMedicAppoByIdPatient)
router.delete('/medicalappointment/delete/doctor/:medicalappoid', verifyTokenDoctor, deleteMedicalAppointmentByDoctor)
router.delete('/medicalappointment/delete/patient/:medicalappoid', verifyToken, deleteMedicalAppointmentByPaciente)
module.exports = router